apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-datasource
  namespace: observability
  labels:
    grafana_datasource: "true"
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.observability.svc.cluster.local
        isDefault: false
        jsonData:
          timeInterval: 30s