apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-datasource
  namespace: observability
  labels:
    grafana_datasource: "true"
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        uid: 464EDC8622694ECA9847
        url: http://prometheus-prometheus.observability:9090
        isDefault: false
        jsonData:
          timeInterval: 30s