
# Refer to the value template: https://github.com/prometheus-community/helm-charts/blob/53fc5e36d4f46f4784a05720eae0eef87c90b5bc/charts/kube-prometheus-stack/values.yaml
kube-prometheus-stack:
  fullnameOverride: prometheus
  prometheusOperator:
    enabled: true

  alertmanager:
    enabled: true

  grafana:
    enabled: false
    adminPassword: admin-1234
    admin:
      existingSecret: ""
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "true"  # Optional if you just match presence of label
        searchNamespace: ALL  # or specific namespace

  prometheus:
    enabled: true
    prometheusSpec:
      retention: 15d
      ruleNamespaceSelector: {}
      ruleSelectorNilUsesHelmValues: false
      ruleSelector:
        matchExpressions:
          - key: sendtomimir
            operator: DoesNotExist
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}
      podMonitorSelectorNilUsesHelmValues: false
      podMonitorSelector: {}
      podMonitorNamespaceSelector: {}
      probeSelectorNilUsesHelmValues: false
      probeSelector: {}
      probeNamespaceSelector: {}
      scrapeConfigSelectorNilUsesHelmValues: false
      scrapeConfigSelector: {}
      scrapeConfigNamespaceSelector: {}

      resources:
        requests:
          cpu: 200m
          memory: 512Mi
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi

      remoteWrite:
        url: http://mimir-nginx.observability/api/v1/push/