apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability
data:
  prometheus.yml: |
    global:
        evaluation_interval: 5s
        scrape_interval: 5s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090

    alerting:
      alertmanagers:
        - static_configs:
            - targets: [ "alertmanager:9093" ]

    rule_files:
      - "/etc/prometheus/alert_rules.yml"